stages:
  - pre-build
  - build
  - test
  - deploy

dummy:
  stage: pre-build
  image: $CI_DOCKER_IMAGE
  script:
    - echo test

build-deb-amd64:
  stage: build
  image: $CI_DOCKER_IMAGE
  before_script:
    - export CI_TARGET_ARCHITECTURE=amd64
  script:
    - ./deps.sh
    - /bin/zlog.sh
    - /bin/scion.sh
  after_script:
    - cp -r /buildroot/debs output-$CI_TARGET_ARCHITECTURE
  artifacts:
    paths:
    - output-amd64/
    expire_in: 1 day

build-deb-arm64:
  only:
    - tags
  stage: build
  image: $CI_DOCKER_IMAGE
  before_script:
    - export CI_TARGET_ARCHITECTURE=arm64
  script:
    - ./deps.sh
    - /bin/zlog.sh
    - /bin/scion.sh
  after_script:
    - cp -r /buildroot/debs output-$CI_TARGET_ARCHITECTURE
  artifacts:
    paths:
    - output-arm64/
    expire_in: 1 day

build-deb-armhf:
  only:
    - tags
  stage: build
  image: $CI_DOCKER_IMAGE
  before_script:
    - export CI_TARGET_ARCHITECTURE=armhf
  script:
    - ./deps.sh
    - /bin/zlog.sh
    - /bin/scion.sh
  after_script:
    - cp -r /buildroot/debs output-$CI_TARGET_ARCHITECTURE
  artifacts:
    paths:
    - output-armhf/
    expire_in: 1 day

deploy-deb:
  stage: deploy
  image: $CI_DOCKER_IMAGE
  script:
    - ls -l output*/debs
